- name: Install Gnome packages
  become: true
  vars:
    common_packages:
      - baobab
      - evince
      - file-roller
      - gnome-calculator
      - gnome-calendar
      - gnome-color-manager
      - gnome-contacts
      - gnome-control-center
      - gnome-disk-utility
      - gnome-keyring
      - gnome-logs
      - gnome-menus
      - gnome-session
      - gnome-settings-daemon
      - gnome-shell
      - gnome-shell-extensions
      - gnome-system-monitor
      - gvfs
      - nautilus
      - xdg-desktop-portal-gnome
      - xdg-user-dirs-gtk
      - papirus-icon-theme
    ansible_distribution_specific_packages:
      Archlinux:
        - gdm
        - loupe
        # NOTE: arch splis gvfs package into modules, we only install the one we want
        - gvfs-goa
        - ttf-fira-code
        # NOTE: required for Ansible dconf module
        - python-psutil
      Debian:
        - gdm3
        # TODO: replace with loupe once available
        - gnome-photos
        - fonts-firacode
        # NOTE: required for Ansible dconf module
        - python3-psutil
      Ubuntu:
        - gdm3
        - loupe
        - fonts-firacode
        # NOTE: required for Ansible dconf module
        - python3-psutil
  ansible.builtin.package:
    name: "{{ common_packages + ansible_distribution_specific_packages[ansible_distribution] }}"
    state: present

- name: Remove unused Gnome packages
  become: true
  ansible.builtin.package:
    name:
      - eog
      - yelp
      - totem
      - sushi
      - simple-scan
      - shotwell
      - rygel
      - orca
      - malcontent
      - gvfs-afc
      - gvfs-google
      - gvfs-wsdd
      - gvfs-onedrive
      - gvfs-nfs
      - gvfs-smb
      - gvfs-wsdd
      - grilo
      - grilo-plugins
      - gnome-clocks
      - gnome-console
      - gnome-weather
      - gnome-user-share
      - gnome-user-docs
      - gnome-tour
      - gnome-text-editor
      - gnome-terminal
      - gnome-software
      - gnome-remote-desktop
      - gnome-music
      - gnome-maps
      - gnome-font-viewer
      - gnome-characters
      - gnome-connections
      - gnome-backgrounds
      - gnome-snapshot
      - gvfs-dnssd
      - gvfs-google
      - gvfs-gphoto2
      - gvfs-onedrive
    state: absent

- name: Enable gdm
  become: true
  vars:
    distribution_specific_gdm_service_name:
      Archlinux: gdm
      Debian: gdm3
      Ubuntu: gdm3
  ansible.builtin.systemd_service:
    name: "{{ distribution_specific_gdm_service_name[ansible_distribution] }}.service"
    enabled: true

- name: Disable avahi-daemon
  become: true
  ansible.builtin.systemd_service:
    name: avahi-daemon
    enabled: false
    state: stopped

- name: Gnome dconf configuration
  vars:
    # NOTE: need to single quote special characters
    dconf_key_values:
      "/org/gnome/desktop/interface/icon-theme": "'Papirus'"
      "/org/gnome/desktop/interface/gtk-theme": "'Adwaita'"
      "/org/gnome/desktop/interface/color-scheme": "'prefer-light'"
      "/org/gnome/desktop/interface/enable-hot-corners": "false"
      "/org/gnome/desktop/interface/monospace-font-name": "'Fira Code'"
      "/org/gnome/desktop/interface/clock-show-seconds": "true"
      "/org/gnome/desktop/interface/clock-show-weekday": "true"
      "/org/gnome/desktop/wm/preferences/button-layout": "'appmenu:minimize,maximize,close'"
      "/org/gnome/desktop/media-handling/autorun-never": "true"
      "/org/gnome/settings-daemon/plugins/media-keys": "['<Control>m']"
      "/org/gnome/mutter/workspaces-only-on-primary": "false"
      "/system/locale/region": "'fr_FR.UTF-8'"
  community.general.dconf:
    key: "{{ item.key | string }}"
    value: "{{ item.value | string }}"
    state: present
  with_items: "{{ dconf_key_values | dict2items }}"
