- name: Blank /etc/apt/sources.list
  become: true
  ansible.builtin.copy:
    content: ""
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'

- name: Add debian repo
  become: true
  ansible.builtin.deb822_repository:
    name: debian
    uris: https://deb.debian.org/debian/
    suites:
      - "{{ ansible_distribution_release }}"
      - "{{ ansible_distribution_release }}-updates"
    # signed_by: /etc/apt/trusted.gpg.d/debian-archive-{{ ansible_distribution_release }}-stable.asc
    components:
      - main
      - contrib
      - non-free
      - non-free-firmware

- name: Add debian-security repo
  become: true
  ansible.builtin.deb822_repository:
    name: debian-security
    uris: https://deb.debian.org/debian-security/
    suites:
      - "{{ ansible_distribution_release }}-security"
    # signed_by: /etc/apt/trusted.gpg.d/debian-archive-{{ ansible_distribution_release }}-security-automatic.asc
    components:
      - main
      - contrib
      - non-free
      - non-free-firmware
