- name: Verify Docker Role
  hosts: all
  tasks:
    - name: Verify zed binary is available
      vars:
        distribution_zed_binary_name:
          Archlinux: zeditor
      ansible.builtin.command:
        argv:
          - "{{ distribution_zed_binary_name[ansible_distribution] | default('zed') }}"
          - --version
      register: zeditor_version_result
      changed_when: false
      failed_when: zeditor_version_result.rc != 0
