- name: Install alacritty
  become: true
  ansible.builtin.package:
    name:
      - alacritty
    state: present

- name: Create alacritty configuration directory
  ansible.builtin.file:
    path: ~/.config/alacritty
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0700"
    state: directory
  register: alacritty_configuration_directory

- name: Create configuration files
  ansible.builtin.copy:
    src: "files/alacritty.toml"
    dest: "{{ alacritty_configuration_directory.path }}/alacritty.toml"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0600"
