- name: Install zed editor
  become: true
  ansible.builtin.package:
    name:
      - zed
    state: present

- name: Create zed configuration directory
  ansible.builtin.file:
    path: ~/.config/zed
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0700"
    state: directory
  register: zed_configuration_directory

- name: Copy zed configuration files
  ansible.builtin.copy:
    src: "files/settings.json"
    dest: "{{ zed_configuration_directory.path }}/settings.json"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0600"

- name: Create environment.d user configuration directory
  ansible.builtin.file:
    path: ~/.config/environment.d/
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0700"
    state: directory
  register: environment_d_configuration_directory

- name: Configure zed as default EDITOR
  ansible.builtin.copy:
    dest: "{{ environment_d_configuration_directory.path }}/zed_editor.conf"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0600"
    content: |
      EDITOR='zeditor --wait'
