- name: Install zed editor
  ansible.builtin.package:
    name:
      - zed
    state: present

- name: Create zed configuration directory
  ansible.builtin.file:
    path: ~/.config/zed/
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0700"
    state: directory
  register: zed_configuration_directory

- name: Create configuration files
  ansible.builtin.copy:
    src: "files/settings.json"
    dest: "{{ zed_configuration_directory.path }}/settings.json"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0600"
