- name: Set distribution_has_zed_package fact
  ansible.builtin.set_fact:
    distribution_has_zed_package: "{{ ansible_distribution in ['Archlinux'] }}"

- name: Install zed editor from package
  become: true
  ansible.builtin.package:
    name:
      - zed
    update_cache: true
  when: distribution_has_zed_package

- name: Install zed editor from Github Releases archive
  when: not distribution_has_zed_package
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/zed-industries/zed/releases/download/v0.173.10/zed-linux-x86_64.tar.gz
    remote_src: true
    dest: "/usr/local/"
    owner: "root"
    group: "root"
    creates: "/usr/local/bin/zed"
    extra_opts:
      - '--strip-components=1'
      - '--show-stored-names'

- name: Create zed configuration directory
  ansible.builtin.file:
    path: ~/.config/zed
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0700"
    state: directory
  register: zed_configuration_directory

- name: Copy zed configuration files
  ansible.builtin.copy:
    src: "files/settings.json"
    dest: "{{ zed_configuration_directory.path }}/settings.json"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0600"

- name: Create environment.d user configuration directory
  ansible.builtin.file:
    path: ~/.config/environment.d/
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0700"
    state: directory
  register: environment_d_configuration_directory

- name: Configure zed as default EDITOR
  ansible.builtin.copy:
    dest: "{{ environment_d_configuration_directory.path }}/zed_editor.conf"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0600"
    content: |
      EDITOR='zeditor --wait'
