# NOTE: Tested on Debian 12 and 13
# sudo apt-get install python-is-python3 python3-debian python3-psutil

- name: Walle Ansible Playbook
  gather_facts: true
  hosts: walle
  tasks:
    - name: Debian apt repository
      ansible.builtin.import_role:
        name: debian_apt_repository
    - name: Locales
      ansible.builtin.import_role:
        name: locales
    - name: Locales
      ansible.builtin.import_role:
        name: unattended_upgrades
    - name: SSH hardening
      become: true
      ansible.builtin.import_role:
        name: devsec.hardening.ssh_hardening
      tags:
        - hardening
    - name: Firewall
      become: true
      ansible.builtin.import_role:
        name: firewall
    - name: Set a hostname
      become: true
      ansible.builtin.hostname:
        name: walle
    - name: Set timezone
      become: true
      community.general.timezone:
        name: Europe/Paris
    - name: Install packages
      become: true
      ansible.builtin.package:
        update_cache: true
        name:
          # NOTE: linux kernel
          - linux-image-amd64
          # NOTE: firmwares
          - amd64-microcode
          - firmware-amd-graphics
          - firmware-realtek
          # NOTE: HW video en/decode*
          - mesa-va-drivers
          - vdpau-driver-all
          # NOTE: AMD Graphics
          - libgl1-mesa-dri
          - libglx-mesa0
          - mesa-vulkan-drivers
          - xserver-xorg-video-all
          # NOTE: system utils
          - sudo
          - bash-completion
          - python-is-python3
          # NOTE: apps
          - dolphin-emu
          - qbittorrent
    - name: Desktop role
      ansible.builtin.import_role:
        name: desktop
    - name: Firefox
      ansible.builtin.import_role:
        name: firefox
    - name: Shell
      ansible.builtin.import_role:
        name: shell
    - name: Xone
      ansible.builtin.import_role:
        name: xone
      tags:
        - xone
    # NOTE: not supported on Debian 13 yet
    # - name: jellyfin_media_player
    #   ansible.builtin.import_role:
    #     name: jellyfin_media_player
